# Generated by Django 3.2.9 on 2022-02-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='No Data', max_length=40)),
                ('Team', models.CharField(max_length=10)),
                ('No', models.IntegerField()),
                ('Image', models.ImageField(blank=True, upload_to='player_image/')),
            ],
        ),
    ]
